export const rwaManagerAbi = [
  // roles
  { "inputs": [], "name": "MEMBER_ROLE", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "internalType": "address", "name": "account", "type": "address" } ], "name": "hasRole", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },

  // core write functions
  { "inputs": [ { "internalType": "uint256", "name": "_requestId", "type": "uint256" }, { "internalType": "uint256", "name": "_assetValue", "type": "uint256" }, { "internalType": "address", "name": "_assetOwner", "type": "address" }, { "internalType": "string", "name": "_tokenURI", "type": "string" } ], "name": "depositRWAAndMintNFT", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "internalType": "uint256", "name": "_requestId", "type": "uint256" }, { "internalType": "uint256", "name": "_tokenAmount", "type": "uint256" } ], "name": "changeNftTradable", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "internalType": "uint256", "name": "_requestId", "type": "uint256" } ], "name": "withdrawRWAAndBurnNFTandCoin", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_to", "type": "address" }, { "internalType": "uint256", "name": "_requestId", "type": "uint256" }, { "internalType": "uint256", "name": "_valueInUSD", "type": "uint256" } ], "name": "updateAssetValue", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_requestId", "type": "uint256" }, { "internalType": "uint256", "name": "_tokenId", "type": "uint256" }, { "internalType": "string", "name": "_imageUri", "type": "string" } ], "name": "updateAssetImageUri", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_to", "type": "address" } ], "name": "mintCoinAgainstEth", "outputs": [], "stateMutability": "payable", "type": "function" },

  // owner/admin
  { "inputs": [ { "internalType": "address", "name": "_newMember", "type": "address" } ], "name": "setNewMember", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_member", "type": "address" } ], "name": "removeMember", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_newPrice", "type": "uint256" } ], "name": "updateEthPrice", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address payable", "name": "_to", "type": "address" }, { "internalType": "uint256", "name": "amount", "type": "uint256" } ], "name": "withdraw", "outputs": [], "stateMutability": "nonpayable", "type": "function" },

  // views
  { "inputs": [], "name": "getContractEthBalance", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "getContractCoinBalance", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" }, { "internalType": "uint256", "name": "_requestId", "type": "uint256" } ], "name": "getUserAssetInfo", "outputs": [ { "components": [ { "internalType": "uint8", "name": "assetType", "type": "uint8" }, { "internalType": "string", "name": "assetName", "type": "string" }, { "internalType": "uint256", "name": "assetId", "type": "uint256" }, { "internalType": "bool", "name": "isLocked", "type": "bool" }, { "internalType": "bool", "name": "isVerified", "type": "bool" }, { "internalType": "uint256", "name": "valueInUSD", "type": "uint256" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "bool", "name": "tradable", "type": "bool" } ], "internalType": "struct RWA_Types.RWA_Info", "name": "", "type": "tuple" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "_requestId", "type": "uint256" } ], "name": "getUserRWAInfo", "outputs": [ { "components": [ { "internalType": "uint8", "name": "assetType", "type": "uint8" }, { "internalType": "string", "name": "assetName", "type": "string" }, { "internalType": "uint256", "name": "assetId", "type": "uint256" }, { "internalType": "bool", "name": "isLocked", "type": "bool" }, { "internalType": "bool", "name": "isVerified", "type": "bool" }, { "internalType": "uint256", "name": "valueInUSD", "type": "uint256" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "bool", "name": "tradable", "type": "bool" } ], "internalType": "struct RWA_Types.RWA_Info", "name": "", "type": "tuple" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_user", "type": "address" }, { "internalType": "uint256", "name": "_requestId", "type": "uint256" } ], "name": "checkIfAssetIsTradable", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "assetId", "type": "uint256" } ], "name": "getUserRWAInfoagainstRequestId", "outputs": [ { "components": [ { "internalType": "uint8", "name": "assetType", "type": "uint8" }, { "internalType": "string", "name": "assetName", "type": "string" }, { "internalType": "uint256", "name": "assetId", "type": "uint256" }, { "internalType": "bool", "name": "isLocked", "type": "bool" }, { "internalType": "bool", "name": "isVerified", "type": "bool" }, { "internalType": "uint256", "name": "valueInUSD", "type": "uint256" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "bool", "name": "tradable", "type": "bool" } ], "internalType": "struct RWA_Types.RWA_Info", "name": "", "type": "tuple" } ], "stateMutability": "view", "type": "function" }
] as const;
