export const rwaVerifiedAssetsAbi = [
  { "inputs": [], "name": "owner", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "MEMBER_ROLE", "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "bytes32", "name": "role", "type": "bytes32" }, { "internalType": "address", "name": "account", "type": "address" } ], "name": "hasRole", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" },

  { "inputs": [ { "internalType": "address", "name": "newMember", "type": "address" } ], "name": "addMember", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "member", "type": "address" } ], "name": "removeMember", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "bytes", "name": "response", "type": "bytes" } ], "name": "registerVerifiedAsset", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "uint256", "name": "assetId", "type": "uint256" } ], "name": "DeRegisterVerifiedAsset", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "uint256", "name": "assetId", "type": "uint256" }, { "internalType": "uint256", "name": "newValueInUSD", "type": "uint256" }, { "internalType": "bool", "name": "isLocked", "type": "bool" }, { "internalType": "bool", "name": "tradable", "type": "bool" } ], "name": "upDateAssetValue", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "owner", "type": "address" } ], "name": "getVerifiedAssets", "outputs": [ { "components": [ { "internalType": "uint8", "name": "assetType", "type": "uint8" }, { "internalType": "string", "name": "assetName", "type": "string" }, { "internalType": "uint256", "name": "assetId", "type": "uint256" }, { "internalType": "bool", "name": "isLocked", "type": "bool" }, { "internalType": "bool", "name": "isVerified", "type": "bool" }, { "internalType": "uint256", "name": "valueInUSD", "type": "uint256" }, { "internalType": "address", "name": "owner", "type": "address" }, { "internalType": "bool", "name": "tradable", "type": "bool" } ], "internalType": "struct RWA_Types.RWA_Info[]", "name": "", "type": "tuple[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "address", "name": "_owner", "type": "address" } ], "name": "isOwnerAllowed", "outputs": [ { "internalType": "bool", "name": "", "type": "bool" } ], "stateMutability": "view", "type": "function" }
] as const;
